### PR TITLE
fix: create Query/Mutation struct as public

### PR DESCRIPTION
**Pull request by fdaciuk**
Hey @nikis05, great job on this crate! Thanks a lot :D

That PR is just a little update to create the root `Query` / `Mutation` as public, if you want to use it in another crate inside of your project :)

After this update, everything is working like a charm, thanks again :D

### CODE REVIEW

**Comment by nikis05** [comment]
Happy to help!

Could you make this configurable? I.e.

```rust
composite_object!(pub Query(UserQueries, TaskQueries));
```

generates a pub type while

```rust
composite_object!(Query(UserQueries, TaskQueries));
```
doesn’t.

also please kindly bump versions of both packages to "0.3" in their Cargo.toml’s

**Comment by fdaciuk** [comment]
I don't know much about macros yet, but I can try =)

**Comment by nikis05** [comment]
@fdaciuk No worries, I'll do it then

**Comment by fdaciuk** [comment]
Yeah, I did try some things @nikis05, but with no success 🙈

**Comment by nikis05** [comment]
@fdaciuk I created a PR for this feature, will merge after it passes checks, closing this one.

**Comment by fdaciuk** [comment]
Thanks a lot! ❤️

**Pull request closed without merging**
